all:
  hosts:
    unknown:
      ansible_host: 192.168.56.6
      ansible_port: 22
      ansible_connection: ssh
      ansible_become: true

  children:
    db:
      hosts:
        db-1: 
          ansible_host: 192.168.56.3
          ansible_port: 22
          ansible_connection: ssh
          ansible_become: true
        # db-2:
        #   ansible_host:
        #   ansible_port:
        #   ansible_connection:
        #   ansible_become:
        # db-3:
        #   ansible_host:
        #   ansible_port:
        #   ansible_connection:
        #   ansible_become:

    be:
      hosts:
        be-1:
          ansible_host: 192.168.56.4
          ansible_port: 22
          ansible_connection: ssh
          ansible_become: true
        # be-2:
        #   ansible_host:
        #   ansible_port:
        #   ansible_connection:
        #   ansible_become:
        # be-3:
        #   ansible_host:
        #   ansible_port:
        #   ansible_connection:
        #   ansible_become:

    fe:
      hosts:
        fe-1:
          ansible_host: 192.168.56.5
          ansible_port: 22
          ansible_connection: ssh
          ansible_become: true
        # fe-2:
        #   ansible_host:
        #   ansible_port:
        #   ansible_connection:
        #   ansible_become:
        # fe-3:
        #   ansible_host:
        #   ansible_port:
        #   ansible_connection:
        #   ansible_become:

    nodes:
      children:
        db:
        fe:
        be:
      hosts:
        unknown:

    valid:
      hosts:
        db-1:
        be-1:
        fe-1: